module.exports = {
  rules: {
    "@stylistic/array-bracket-newline": ["error", { multiline: true }],
    "@stylistic/array-bracket-spacing": ["error", "never"],
    "@stylistic/array-element-newline": ["error", "consistent"],
    "@stylistic/arrow-parens": ["error", "always"],
    "@stylistic/arrow-spacing": ["error", { before: true, after: true }],
    "@stylistic/block-spacing": ["error", "always"],
    "@stylistic/brace-style": ["error", "1tbs", { allowSingleLine: true }],
    "@stylistic/comma-dangle": ["error", "only-multiline"],
    "@stylistic/comma-spacing": ["error", { before: false, after: true }],
    "@stylistic/comma-style": ["error", "last"],
    "@stylistic/computed-property-spacing": ["error", "never"],
    "@stylistic/curly-newline": ["error", { consistent: true }],
    "@stylistic/dot-location": ["error", "property"],
    "@stylistic/eol-last": ["error", "always"],
    "@stylistic/function-call-argument-newline": ["error", "consistent"],
    "@stylistic/function-call-spacing": ["error", "never"],
    "@stylistic/function-paren-newline": ["off"],
    "@stylistic/generator-star-spacing": [
      "error",
      { before: false, after: true },
    ],
    "@stylistic/implicit-arrow-linebreak": ["off"],
    "@stylistic/indent": ["off"],
    "@stylistic/indent-binary-ops": ["off"],
    "@stylistic/key-spacing": ["off"],
    "@stylistic/keyword-spacing": ["error", { before: true, after: true }],
    "@stylistic/line-comment-position": ["off"],
    "@stylistic/lines-around-comment": ["off"],
    "@stylistic/linebreak-style": ["error", "unix"],
    "@stylistic/lines-between-class-members": [
      "error",
      {
        enforce: [
          { blankLine: "always", prev: "*", next: "method" },
          { blankLine: "always", prev: "method", next: "*" },
        ],
      },
    ],
    "@stylistic/max-len": ["off"],
    "@stylistic/max-statements-per-line": ["error", { max: 1 }],
    "@stylistic/member-delimiter-style": [
      "error",
      {
        multiline: {
          delimiter: "semi",
          requireLast: true,
        },
        singleline: {
          delimiter: "semi",
          requireLast: false,
        },
        multilineDetection: "brackets",
      },
    ],
    "@stylistic/multiline-comment-style": ["error", "starred-block"],
    "@stylistic/multiline-ternary": [
      "error",
      "always-multiline",
      {
        ignoreJSX: true,
      },
    ],
    "@stylistic/new-parens": ["error", "always"],
    "@stylistic/newline-per-chained-call": ["off"],
    "@stylistic/no-confusing-arrow": ["off"],
    "@stylistic/no-extra-parens": ["off"],
    "@stylistic/no-extra-semi": ["error"],
    "@stylistic/no-floating-decimal": ["error"],
    "@stylistic/no-mixed-operators": [
      "error",
      {
        groups: [
          ["&", "|", "^", "~", "<<", ">>", ">>>"],
          ["&&", "||"],
        ],
        allowSamePrecedence: false,
      },
    ],
    "@stylistic/no-mixed-spaces-and-tabs": ["error", "smart-tabs"],
    "@stylistic/no-multi-spaces": ["error"],
    "@stylistic/no-multiple-empty-lines": ["warn", { max: 2 }],
    "@stylistic/no-tabs": ["error"],
    "@stylistic/no-trailing-spaces": ["error"],
    "@stylistic/no-whitespace-before-property": ["error"],
    "@stylistic/nonblock-statement-body-position": ["off"],
    "@stylistic/object-curly-newline": ["off"],
    "@stylistic/object-curly-spacing": ["error", "always"],
    "@stylistic/object-property-newline": [
      "error",
      { allowAllPropertiesOnSameLine: true },
    ],
    "@stylistic/one-var-declaration-per-line": ["off"],
    "@stylistic/operator-linebreak": [
      "error",
      "after",
      {
        overrides: {
          "?": "ignore",
          ":": "ignore",
          "&": "ignore",
          "|": "ignore",
        },
      },
    ],
    "@stylistic/padded-blocks": ["off"],
    "@stylistic/padding-line-between-statements": ["off"],
    "@stylistic/quote-props": ["error", "as-needed"],
    "@stylistic/quotes": [
      "error",
      "double",
      {
        avoidEscape: true,
        allowTemplateLiterals: "avoidEscape",
      },
    ],
    "@stylistic/rest-spread-spacing": ["error", "never"],
    "@stylistic/semi": ["error", "always"],
    "@stylistic/semi-spacing": ["error", { before: false, after: true }],
    "@stylistic/semi-style": ["error", "last"],
    "@stylistic/space-before-blocks": ["error", "always"],
    "@stylistic/space-before-function-paren": [
      "error",
      {
        anonymous: "always",
        named: "never",
        asyncArrow: "always",
        catch: "always",
      },
    ],
    "@stylistic/space-in-parens": ["error", "never"],
    "@stylistic/space-infix-ops": ["error", { int32Hint: false }],
    "@stylistic/space-unary-ops": ["error", { words: true, nonwords: false }],
    "@stylistic/spaced-comment": ["error", "always"],
    "@stylistic/switch-colon-spacing": [
      "error",
      { after: true, before: false },
    ],
    "@stylistic/template-curly-spacing": ["error", "never"],
    "@stylistic/template-tag-spacing": ["error", "never"],
    "@stylistic/type-annotation-spacing": ["off"],
    "@stylistic/type-generic-spacing": ["error"],
    "@stylistic/type-named-tuple-spacing": ["error"],
    "@stylistic/wrap-iife": ["error", "any"],
    "@stylistic/wrap-regex": ["off"],
    "@stylistic/yield-star-spacing": ["error", { before: true, after: false }],
  },
};
